"""Regulatory-compliance mapping and model cards.

Maps TrustFedGNN's components to the requirements of two international
trustworthy-AI frameworks referenced by the target collection -- the EU AI Act
and the NIST AI Risk Management Framework -- and generates a Mitchell et al.
(2019) style model card. This operationalises "accountability, transparency and
regulatory compliance" as a concrete, auditable artifact rather than prose.
"""
from __future__ import annotations

from typing import Dict, List

# component -> which requirement it helps satisfy + the evidence produced
EU_AI_ACT = [
    ("Art. 10 - Data & data governance",
     "Non-IID federated silos keep raw data local; sensitive attribute excluded "
     "from features; documented dataset provenance and base-rate gaps.",
     ["FSER", "FTGD", "data loaders"]),
    ("Art. 13 - Transparency & information",
     "Per-edge FSER attention and feature-level disparity attribution expose why "
     "a decision is made; model card documents intended use and metrics.",
     ["explainability", "model card"]),
    ("Art. 14 - Human oversight",
     "Explicit, human-set fairness budget tau and privacy budget epsilon; "
     "Pareto trade-off curves let an operator choose the operating point.",
     ["BFWA", "human-in-the-loop budget"]),
    ("Art. 15 - Accuracy, robustness & cybersecurity",
     "Byzantine-robust aggregation (robust_bfwa) with reported accuracy retention "
     "under poisoning/fairness attacks; RDP privacy guarantee.",
     ["robust_bfwa", "attacks study", "RDP accountant"]),
]

NIST_AI_RMF = [
    ("GOVERN", "Fairness/privacy budgets and audit logging make governance choices explicit and recorded.",
     ["config", "audit log"]),
    ("MAP", "Threat model (Byzantine + fairness poisoning) and subgroup-disparity context are documented.",
     ["attacks", "dataset meta"]),
    ("MEASURE", "DPD/EOD/EO, RDP epsilon, attack-retention, ECE and a composite trust score are all measured.",
     ["metrics", "trust_score", "uncertainty"]),
    ("MANAGE", "Robust aggregation + fairness constraint actively mitigate measured risks each round.",
     ["robust_bfwa", "BFWA"]),
]


def compliance_matrix() -> Dict[str, List[Dict]]:
    def fmt(rows):
        return [{"requirement": r, "how_addressed": h, "components": c} for r, h, c in rows]
    return {"eu_ai_act": fmt(EU_AI_ACT), "nist_ai_rmf": fmt(NIST_AI_RMF)}


def model_card(config, result: Dict, dataset_meta: Dict = None) -> str:
    f = result.get("final", result)
    meta = dataset_meta or {}
    def g(k, d="n/a"):
        v = f.get(k, d)
        return f"{v:.4f}" if isinstance(v, float) else v
    eps = f"{f.get('epsilon'):.2f}" if f.get("epsilon") else "no DP"
    return f"""# Model Card -- TrustFedGNN

## Model details
- Architecture: {config.get('model')} ({config.get('num_layers')} layers, hidden {config.get('hidden_channels')})
- Federated setup: {config.get('num_clients')} clients, {config.get('rounds')} rounds, aggregator={config.get('aggregator')}
- Privacy: (epsilon={eps}, delta={config.get('dp_delta')}) via statistic-level RDP accounting

## Intended use
Collaborative fraud / high-stakes risk detection across institutions that cannot
share raw data, where demographic fairness and privacy are required.

## Training data
- Dataset: {config.get('dataset')}  (sensitive attribute: {meta.get('sensitive_name','see dataset')})
- Positive class: {meta.get('positive_meaning','target outcome')}

## Evaluation (pooled global test set)
- AUC-ROC: {g('auc')}    AP: {g('ap')}    F1: {g('f1')}    FPR@80%TPR: {g('fpr@80tpr')}
- Demographic Parity Diff (DPD): {g('dpd')}
- Equal Opportunity Diff (EOD): {g('eod')}    Equalized Odds: {g('eo')}

## Ethical considerations & limitations
- Sensitive attributes are binary; multi-valued attributes use one-vs-rest.
- The privacy guarantee protects the demographic-parity signal; it is not a
  guarantee over arbitrary functions of the data.
- Fairness is enforced for demographic parity / equalised odds; other fairness
  notions may trade off differently.

## Regulatory alignment
See the EU AI Act / NIST AI RMF compliance matrix generated by
`src.trust.compliance.compliance_matrix()`.
"""
